include: package:very_good_analysis/analysis_options.yaml
linter:
  rules:
    public_member_api_docs: false
    sort_constructors_first: false
    avoid_dynamic_calls: false
    constant_identifier_names: false
    cascade_invocations: false
    lines_longer_than_80_chars: false
    prefer_typing_uninitialized_variables: false
    directives_ordering: false