name: projects
description: ONLYOFFICE Projects on Mobile.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0+97

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.17.0 
  get: ^4.3.7
  get_it: ^7.2.0
  get_storage: ^2.0.3
  # for http requests
  http: ^0.13.0
  # to use svg icons
  # flutter_svg: ^0.20.0-nullsafety.3
  flutter_svg: ^0.22.0
  # for storing important data
  flutter_secure_storage: ^4.2.0
  json_serializable: ^3.5.1 
  json_annotation: ^3.1.1
  source_gen: 0.9.10+2 
  
  pull_to_refresh: ^1.6.4
  visibility_detector: ^0.2.0
  # shimmer for loading
  shimmer: ^1.1.2
  drop_cap_text: ^1.0.7
  # read more button
  readmore: ^2.0.0
  # bottom sheet with dynamic size
  bottom_sheet: ^0.0.1-dev.8
  darq: ^1.1.1
  # to open app in App Stores //need to replace
  launch_review: ^3.0.1
  # formatting input in textfields // надо поменять, тк он и сам текст форматирует
  flutter_masked_text: ^0.8.0
  # for biometric authentication
  local_auth: ^1.1.6
  # to get device location country
  devicelocale: ^0.4.1
  # for sms 2FA
  flutter_libphonenumber: ^1.0.4
  tabbar: ^0.1.1
  extended_tabs: ^2.2.0
  cached_network_image: ^3.0.0
  firebase_core: ^1.6.0
  firebase_analytics: ^8.3.2
  
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0

  path_provider: ^2.0.2
  flutter_downloader: ^1.6.1
  external_app_launcher: ^0.0.1
  url_launcher: ^6.0.9
  # info about app version
  package_info: ^2.0.2
  # info about device
  device_info: ^2.0.2
  # clear cache
  flutter_cache_manager: ^3.1.2
  
  # app localization
  easy_localization: ^3.0.0
  # to restart the application correctly
  restart_app: ^1.0.3  

  event_hub: ^0.1.1
  connectivity_plus: ^1.1.0
  html_editor_enhanced: ^2.3.0
  flutter_widget_from_html: ^0.7.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.0.0
  very_good_analysis: ^2.0.3
  flutter_native_splash: ^1.2.0
  # pedantic: ^1.11.0
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  generate: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - lib/assets/images/
    - lib/assets/images/icons/
    - lib/assets/images/images/
    - lib/assets/images/icons/tab_bar/
    - lib/assets/images/icons/project_statuses/
    - lib/assets/images/icons/task_statuses/
    - lib/assets/images/icons/task_detailed/
    - lib/assets/images/icons/folders/
    - lib/assets/images/icons/empty_state/
    - lib/assets/splash/
    - lib/l10n/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages


#   name: projects
# description: ONLYOFFICE Projects on Mobile.

# publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# version: 1.0.0+1

# environment:
#   sdk: ">=2.7.0 <3.0.0"

# dependencies:
#   flutter:
#     sdk: flutter

#   http: 0.12.2
#   flutter_svg: 0.19.1
#   flutter_secure_storage: 3.3.5 
#   get_it: ^4.0.2
#   provider: ^4.1.3
#   cupertino_icons: ^1.0.0

# dev_dependencies:
#   flutter_test:
#     sdk: flutter
    
# flutter:
#   uses-material-design: true
#   assets:
#     - resources/logo_new.svg