name: projects
description: ONLYOFFICE Projects on Mobile.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html

version: 2.0.0+241

environment:
  sdk: '>=2.16.0 <3.0.0'
  flutter: '>=2.5.0'

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.17.0 
  open_file: 3.2.1
  get: ^4.6.1
  get_it: ^7.2.0
  shared_preferences: ^2.0.13
  # for http requests
  http: ^0.13.4
  # to use svg icons
  flutter_svg: ^1.0.3
  # for storing important data
  flutter_secure_storage: ^5.0.2
  json_serializable: ^6.0.1 
  json_annotation: ^4.3.0
  source_gen: ^1.1.1 
  
  pull_to_refresh: ^2.0.0
  visibility_detector: ^0.2.2
  # shimmer for loading
  shimmer: ^2.0.0
  drop_cap_text: ^1.1.3
  # read more button
  readmore: ^2.1.0
  # bottom sheet with dynamic size
  bottom_sheet: ^1.0.4
  darq: ^1.1.1
  # to open app in App Stores //need to replace
  launch_review: ^3.0.1
  # formatting input in textfields // надо поменять, тк он и сам текст форматирует
  flutter_masked_text2: ^0.9.1
  # for biometric authentication
  local_auth: ^2.0.0
  # to get device location country
  devicelocale: ^0.5.0
  # for sms 2FA
  flutter_libphonenumber: ^1.2.1
#  tabbar: ^0.1.1
  extended_tabs: ^2.3.0
  cached_network_image: ^3.1.0+1
  firebase_core: ^1.10.0
  firebase_analytics: ^8.3.4
  firebase_remote_config: ^1.0.2
  http_client_helper: ^2.0.2

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.4

  path_provider: ^2.0.10
  flutter_downloader: ^1.7.4
  url_launcher: ^6.0.20
  # info about app version
  package_info: ^2.0.2
  # info about device
  device_info_plus: ^3.2.2
  # clear cache
  flutter_cache_manager: ^3.3.0
  flutter_platform_widgets: ^1.20.0
  file_picker: ^4.5.1
  share_plus: ^4.0.4
  
  # app localization
  easy_localization: ^3.0.0


  #  event_hub: ^0.1.1
  event_hub:
    git:
      url: git://github.com/ONLYOFFICE/event_hub
  connectivity_plus: ^2.2.1
  html_editor_enhanced: ^2.4.0+1
  flutter_widget_from_html: ^0.8.5
  collection: ^1.15.0-nullsafety.4
  webview_cookie_manager: ^2.0.6

  modal_bottom_sheet: ^2.0.0
  settings_ui: ^2.0.2
  android_path_provider: ^0.3.0
  permission_handler: ^9.2.0

  quick_actions: ^0.6.0+11
  

dependency_overrides:
  flutter_colorpicker: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.5
  very_good_analysis: ^2.4.0
  flutter_native_splash: ^1.3.1
  # pedantic: ^1.11.0
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  generate: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - lib/assets/images/
    - lib/assets/images/icons/
    - lib/assets/images/images/
    - lib/assets/images/icons/tab_bar/
    - lib/assets/images/icons/project_statuses/
    - lib/assets/images/icons/discussion_statuses/
    - lib/assets/images/icons/task_statuses/
    - lib/assets/images/icons/task_detailed/
    - lib/assets/images/icons/folders/
    - lib/assets/images/icons/empty_state/
    - lib/assets/images/icons/user_atributes/
    - lib/assets/images/icons/file_icons/
    - lib/assets/splash/
    - lib/l10n/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages