import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:get/get.dart';
import 'package:projects/domain/controllers/login_controller.dart';
import 'package:projects/presentation/shared/theme/custom_theme.dart';
import 'package:projects/presentation/shared/theme/text_styles.dart';
import 'package:projects/presentation/shared/widgets/app_icons.dart';
import 'package:projects/presentation/shared/widgets/styled_app_bar.dart';

import 'package:projects/presentation/views/authentication/widgets/tfacode_form.dart';
import 'package:projects/presentation/views/authentication/widgets/wide_button.dart';
import 'package:flutter_masked_text/flutter_masked_text.dart';

class CodeView extends StatelessWidget {
  CodeView({Key key}) : super(key: key);
  @override
  Widget build(BuildContext context) {
    var controller = Get.find<LoginController>();

    var codeController = MaskedTextController(mask: '000 000');

    return Scaffold(
      appBar: StyledAppBar(),
      body: SingleChildScrollView(
        child: Column(
          children: [
            SizedBox(height: Get.height * 0.1096),
            // AppIcon(icon: PngIcons.code_light),
            SizedBox(height: Get.height * 0.0347),
            Text('Двухфакторная\nаутентификация',
                textAlign: TextAlign.center,
                style: TextStyleHelper.headline5(
                    color: Theme.of(context).customColors().onSurface)),
            SizedBox(height: Get.height * 0.0222),
            Padding(
              padding: const EdgeInsets.symmetric(horizontal: 40),
              child: Text(
                _text,
                textAlign: TextAlign.center,
                style: TextStyleHelper.body2(
                    color: Theme.of(context)
                        .customColors()
                        .onSurface
                        .withOpacity(0.6)),
              ),
            ),
            SizedBox(height: Get.height * 0.0333),
            Padding(
              padding: const EdgeInsets.symmetric(horizontal: 36),
              child: TextField(
                controller: codeController,
                keyboardType: TextInputType.number,
                textAlign: TextAlign.center,
                style: TextStyleHelper.subtitle1(),
              ),
            ),
            SizedBox(height: Get.height * 0.055),
            Padding(
              padding: const EdgeInsets.symmetric(horizontal: 40),
              child: WideButton(
                text: 'CONFIRM',
                onPressed: () async =>
                    await controller.sendCode(codeController.text),
              ),
            ),
            // Center(
            //   child: Container(
            //     color: Theme.of(context).backgroundColor,
            //     child: Padding(
            //       padding: const EdgeInsets.all(36.0),
            //       child: Column(
            //         mainAxisAlignment: MainAxisAlignment.center,
            //         children: <Widget>[
            //           const SizedBox(height: 10.0),
            // CodeForm()
            //         ],
            //       ),
            //     ),
            //   ),
            // ),
          ],
        ),
      ),
    );
  }
}

String _text =
    'Copy the code generated by Google Authenticator application and insert it to the input field';
